[package]
name = "tokio-modbus"
description = "Tokio-based Modbus library"
version = "0.4.0"
authors = ["slowtec GmbH", "Markus Kohlhase <markus.kohlhase@slowtec.de>"]
license = "MIT/Apache-2.0"
readme = "README.md"
keywords = ["fieldbus", "modbus", "hardware", "automation"]
homepage = "https://github.com/slowtec/tokio-modbus"
repository = "https://github.com/slowtec/tokio-modbus"
edition = "2018"

[dependencies]
async-trait = "0.1"
byteorder = "1"
bytes = "1"
futures = { version = "0.3", optional = true }
futures-util = { version = "0.3", optional = true, default-features = false }
log = "0.4"
smallvec = { version = "1", default-features = false }
socket2 = { version = "0.4", optional = true, default-features = false }
tokio = { version = "1", default-features = false }
# Disable default-features to exclude unused dependency on libudev
tokio-serial = { version = "5.4.1", optional = true, default-features = false }
tokio-util = { version = "0.6", features = ["codec"] }

[dev-dependencies]
env_logger = "0.9"
futures = "0.3"
tokio = { version = "1", features = ["net", "macros", "io-util", "rt"] }

[features]
default = ["tcp", "rtu", "sync"]
rtu = ["tokio-serial", "futures-util/sink"]
tcp = ["tokio/net", "futures-util/sink"]
sync = []
server = ["futures", "socket2/all", "tokio/rt", "tokio/rt-multi-thread"]
tcp-server-unstable = ["server"]

[badges]
travis-ci = { repository = "slowtec/tokio-modbus" }
coveralls = { repository = "slowtec/tokio-modbus", branch = "master", service = "github" }
maintenance = { status = "actively-developed" }

[[example]]
name = "rtu-client-shared-context"
path = "examples/rtu-client-shared-context.rs"
required-features = ["rtu"]

[[example]]
name = "rtu-client-sync"
path = "examples/rtu-client-sync.rs"
required-features = ["rtu", "sync"]

[[example]]
name = "rtu-client"
path = "examples/rtu-client.rs"
required-features = ["rtu"]

[[example]]
name = "tcp-client-custom-fn"
path = "examples/tcp-client-custom-fn.rs"
required-features = ["tcp"]

[[example]]
name = "tcp-client-sync"
path = "examples/tcp-client-sync.rs"
required-features = ["tcp", "sync"]

[[example]]
name = "tcp-client"
path = "examples/tcp-client.rs"
required-features = ["tcp"]

[[example]]
name = "tcp-server"
path = "examples/tcp-server.rs"
required-features = ["tcp", "server", "tcp-server-unstable"]
