[package]
name = "tokio-modbus"
description = "Tokio-based Modbus library"
version = "0.3.5"
authors = ["slowtec GmbH", "Markus Kohlhase <markus.kohlhase@slowtec.de>"]
license = "MIT/Apache-2.0"
readme = "README.md"
keywords = ["fieldbus", "modbus", "hardware", "automation"]
homepage = "https://github.com/slowtec/tokio-modbus"
repository = "https://github.com/slowtec/tokio-modbus"
edition = "2018"

[dependencies]
bytes = "0.5"
byteorder = "1"
futures = "0.3.1"
log = "0.4"
smallvec = { version = "0.6", default-features = false }
tokio = { version = "0.2", features = ["tcp", "rt-core"] }
tokio-util = { version = "0.2", features = ["codec"] }
net2 = "0.2"
futures-util = "0.3.1"

# Disable default-features to exclude unused dependency on libudev
tokio-serial = { version = "4.3.3", optional = true, default-features = false }

[dev-dependencies]
env_logger = "0.6"

[features]
default = ["tcp", "rtu", "sync"]
rtu = ["tokio-serial"]
tcp = []
sync = []

[badges]
travis-ci = { repository = "slowtec/tokio-modbus" }
coveralls = { repository = "slowtec/tokio-modbus", branch = "master", service = "github" }
maintenance = { status = "actively-developed" }
